/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponentCase {}
  interface MyComponentCaseAttributes extends StencilHTMLAttributes {}

  interface MyComponentChild {}
  interface MyComponentChildAttributes extends StencilHTMLAttributes {}

  interface MyComponent {}
  interface MyComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyComponentCase': Components.MyComponentCase;
    'MyComponentChild': Components.MyComponentChild;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'my-component-case': Components.MyComponentCaseAttributes;
    'my-component-child': Components.MyComponentChildAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLMyComponentCaseElement extends Components.MyComponentCase, HTMLStencilElement {}
  var HTMLMyComponentCaseElement: {
    prototype: HTMLMyComponentCaseElement;
    new (): HTMLMyComponentCaseElement;
  };

  interface HTMLMyComponentChildElement extends Components.MyComponentChild, HTMLStencilElement {}
  var HTMLMyComponentChildElement: {
    prototype: HTMLMyComponentChildElement;
    new (): HTMLMyComponentChildElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-component-case': HTMLMyComponentCaseElement
    'my-component-child': HTMLMyComponentChildElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'my-component-case': HTMLMyComponentCaseElement;
    'my-component-child': HTMLMyComponentChildElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
